apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner-role
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["pods", "services", "deployments", "replicasets", "pods/exec", "secrets", "configmaps", "namespaces", "jobs"]
  verbs: ["create", "delete", "get", "list", "watch", "patch", "update", "execute"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner-role-binding
subjects:
- kind: ServiceAccount
  name: gitlab-ci
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: gitlab-runner-role
  apiGroup: rbac.authorization.k8s.io
