apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-ci-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "secrets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
