apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-ci-role-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: gitlab-ci
  namespace: kube-system
roleRef:
  kind: Role
  name: gitlab-ci-role
  apiGroup: rbac.authorization.k8s.io
